We'll cover a few categories of basic array manipulations here:

- **Attributes of arrays**: Determining the size, shape, memory consumption, and data types of arrays
- **Indexing of arrays**: Getting and setting the value of individual array elements
- **Slicing of arrays**: Getting and setting smaller subarrays within a larger array
- **Reshaping of arrays**: Changing the shape of a given array
- **Joining and splitting of arrays**: Combining multiple arrays into one, and splitting one array into many

- `ndim`: number of dimensions
- `shape`: size of each dimension
- `size`: size of the array
- `itemsize`: size (in bytes) of each array element
- `nbytes`: size (in bytes) of the array

# NumPy Array Attributes

In [51]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int64


# Array Indexing: Accessing Single Elements

In [4]:
x1

array([5, 0, 3, 3, 7, 9])

In [5]:
x1[0]

5

In [6]:
x1[4]

7

In [7]:
x1[-1]

9

In [8]:
x1[-2]

7

In [9]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [10]:
x2[0,0]

3

In [11]:
x2[2,0]

1

In [12]:
x2[2,-1]

7

Values can also be modified using the above index notation:

In [13]:
x2[0,0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

**NOTE**: NumPy have a fixed type. Attempting to insert a floating-point value to an integer array will result in silent truncating!!

In [14]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

# Array Slicing: Accessing Subarrays

`x[start:stop:step]`

Default `start=0`, `stop= size of dimension`, `step=1`

## One-dimensional subarrays

In [15]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [17]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [18]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [19]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [20]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [21]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [22]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

## Multi-dimensional subarrays

In [23]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [24]:
x2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [25]:
x2[:3, ::2]  # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [26]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [27]:
print(x2[:, 0])  # first column of x2

[12  7  1]


In [28]:
print(x2[0, :])  # first row of x2

[12  5  2  4]


In [29]:
print(x2[0])  # equivalent to x2[0, :]

[12  5  2  4]


## Subarrays as no-copy views

One important–and extremely useful–thing to know about array slices is that they return views rather than copies of the array data. This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies. 

- If you modify a sub-array, the original array is changed!
- BUT, means you can access and process pieces of large datasets at a time

In [30]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [31]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [32]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [33]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Creating copies of arrays

In [34]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [35]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [36]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


# Reshaping of Arrays

- Where possible, the `reshape` method will use a no-copy view of the intitial array.

- `newaxis` converts a one-dimensional array into a two-dimensional row or column matrix

In [37]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
x = np.array([1, 2, 3])
print(x)
# row vector via reshape
x.reshape((1, 3))

[1 2 3]


array([[1, 2, 3]])

In [42]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [43]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [44]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

# Array Concatenation and Splitting

## Concatenation of arrays

- `np.concatenate`: Takes a tuple or list of arrays as its first argument
- `np.hstack`: For working with arrays of mixed dimensions. Horizontal stack
- `np.vstack`: For working with arrays of mixed dimensions. Vertical stack

In [45]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [46]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [48]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [49]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [59]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [60]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [61]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

## Splitting of arrays

- `np.split`
- `np.hsplit`
- `np.vsplit`

In [62]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [63]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [65]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
