# NumPy

Python uses dynamic typing. Meaning a variable does not have to be explicitly declared.Data types are inferred.

In [ ]:
# /* C code */
# int result = 0;
# for(int i=0; i<100; i++){
#     result += i;
# }

In [ ]:
# Python code
x = 4
x = "four"

# A Python Integer Is More Than Just an Integer

In [ ]:
struct _longobject {
    long ob_refcnt;
    PyTypeObject *ob_type;
    size_t ob_size;
    long ob_digit[1];
};

A single integer in Python 3.4 actually contains four pieces:

1. `ob_refcnt`, a reference count that helps Python silently handle memory allocation and deallocation
2. `ob_type`, which encodes the type of the variable
3. `ob_size`, which specifies the size of the following data members
4. `ob_digit`, which contains the actual integer value that we expect the Python variable to represent.

A **Python integer** is a pointer to a position in memory containing all the Python object information, including the bytes that contain the integer value

A **C integer** is essentially a label for a position in memory whose bytes encode an integer value

# A Python List Is More Than Just a List

**List**: Mutable, multi-elemrnt container

Flexibility comes at a cost: to allow these flexible types, each item in the list must contain its own type info, reference count, and other information–that is, each item is a complete Python object.

The array essentially contains a single pointer to one contiguous block of data. The Python list, on the other hand, contains a pointer to a block of pointers, each of which in turn points to a full Python object like the Python integer we saw earlier.

In [3]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

# Fixed-Type Arrays in Python

The built-in `array` module (available since Python 3.3) can be used to create dense arrays of a uniform type:

Where `i` is specifying type as integer.

In [4]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Creating Arrays from Python Lists

- NumPy is constrained to arrays that all contain the same type. If types do not match, NumPy will upcast if possible (ex: integers are up-cast to floating)
- `dtype`
- Can be multi-dimensional

In [5]:
import numpy as np

In [8]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [7]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

Use `dtype` to explicitly set the data type of the resulting array.

In [9]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [10]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

# Creating Arrays from Scratch

In [11]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [17]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.393716  , 0.95274236, 0.01610867],
       [0.82335594, 0.60916636, 0.91853448],
       [0.31360351, 0.59160562, 0.76432932]])

In [20]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 1.2044146 ,  0.94798525,  1.03064888],
       [ 0.22988173,  0.34024593,  1.6900273 ],
       [-0.17978872,  1.11387848,  0.8847242 ]])

In [21]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[6, 9, 7],
       [2, 6, 3],
       [5, 8, 2]])

In [22]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

# NumPy Standard Data Types


**Data type	Description**

`bool_`	Boolean (True or False) stored as a byte

`int_`	Default integer type (same as C long; normally either int64 or `int32)`

`intc`	Identical to C int (normally int32 or int64)

`intp`	Integer used for indexing (same as C ssize_t; normally either 

`int32` or int64)

`int8`	Byte (-128 to 127)

`int16`	Integer (-32768 to 32767)

`int32`	Integer (-2147483648 to 2147483647)

`int64`	Integer (-9223372036854775808 to 9223372036854775807)

`uint8`	Unsigned integer (0 to 255)

`uint16`	Unsigned integer (0 to 65535)

`uint32`	Unsigned integer (0 to 4294967295)

`uint64`	Unsigned integer (0 to 18446744073709551615)

`float_`	Shorthand for float64.

`float16`	Half precision float: sign bit, 5 bits exponent, 10 bits mantissa

`float32`	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa

`float64`	Double precision float: sign bit, 11 bits exponent, 52 bits mantissa

`complex_`	Shorthand for complex128.

`complex64`	Complex number, represented by two 32-bit floats

`complex128`	Complex number, represented by two 64-bit floats